// Generates design/tokens.css from src/tokens so the Claude Design previews
// never drift from the React Native tokens. Run: npm run build:css
import { writeFileSync } from 'node:fs';
import { tokens } from '../src/tokens/index.ts';

const kebab = (s: string) => s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
const lines: string[] = [];
const v = (name: string, value: string | number) => lines.push(`  --${name}: ${value};`);

for (const [k, val] of Object.entries(tokens.colors)) v(`color-${kebab(k)}`, val);
for (const [k, val] of Object.entries(tokens.spacing)) v(`space-${k}`, `${val}px`);
for (const [k, val] of Object.entries(tokens.safeArea)) v(`safe-${k}`, `${val}px`);
for (const [k, val] of Object.entries(tokens.radii)) v(`radius-${k}`, `${val}px`);
// Breakpoints can't drive media queries from custom properties; these document the numbers for previews.
for (const [k, val] of Object.entries(tokens.breakpoints)) v(`breakpoint-${k}`, `${val}px`);
for (const [k, val] of Object.entries(tokens.gutters)) v(`gutter-${k}`, `${val}px`);
for (const [k, t] of Object.entries(tokens.typography)) {
  v(`type-${k}-size`, `${t.fontSize}px`);
  v(`type-${k}-line`, `${t.lineHeight}px`);
  v(`type-${k}-weight`, t.fontWeight);
  v(`type-${k}-tracking`, `${t.letterSpacing}px`);
}
v('focus-scale', tokens.focus.scale);
v('focus-ring-width', `${tokens.focus.ringWidth}px`);
v('focus-ring-offset', `${tokens.focus.ringOffset}px`);
for (const [k, val] of Object.entries(tokens.motion)) v(`motion-${k}`, `${val}ms`);
for (const [k, a] of Object.entries(tokens.artwork)) {
  v(`art-${k}-width`, `${a.width}px`);
  v(`art-${k}-height`, `${Math.round(a.width / a.aspectRatio)}px`);
}
v('canvas-width', `${tokens.canvas.width}px`);
v('canvas-height', `${tokens.canvas.height}px`);

const typeClasses = Object.keys(tokens.typography)
  .map(
    (k) =>
      `.t-${k} { font-size: var(--type-${k}-size); line-height: var(--type-${k}-line); ` +
      `font-weight: var(--type-${k}-weight); letter-spacing: var(--type-${k}-tracking); }`,
  )
  .join('\n');

const css = `/* GENERATED by scripts/build-css.mts from src/tokens — do not edit by hand. */
:root {
${lines.join('\n')}
  --font-sans: -apple-system, BlinkMacSystemFont, "Roboto", "Segoe UI", system-ui, sans-serif;
}

${typeClasses}
`;

writeFileSync(new URL('../design/tokens.css', import.meta.url), css);
console.log(`wrote design/tokens.css (${lines.length} variables)`);
